name: madek/app

windows:
  2:
    name: jvm-main
    command: >
      rm -rf target &&
      sleep 5 &&
      lein do repl
    post_command_send_keys: |
      (-main)
  3:
    name: electron-app
    command: >
      sleep 30 &&
      ./electron/Electron.app/Contents/MacOS/Electron app/dev
  5:
    name: electron-front
    command: >
      rm -rf \
        app/dev/js/front.js \
        app/dev/js/out_front.js &&
      lein trampoline figwheel electron-front-dev
  6:
    name: electron-main
    command: >
      rm -rf app/dev/js/out_main app/dev/js/main.js &&
      lein trampoline cljsbuild auto electron-main-dev
  7:
    name: css
    command: lein sass watch
