name: madek/app

windows:
  2:
    name: repl
    command: |
      sleep 5 && lein do repl
    post_command_send_keys: |
      (-main)
  3:
    name: figwheel repl
    command: >
      ./bin/build-electron-dev
      && lein do descjop-figwheel
  5:
    name: electron app
    command: >
      sleep 60
      && ./electron/Electron.app/Contents/MacOS/Electron app/dev


