jobs:
  build:
    name: Build the App
    run_when:
      on any branch:
        type: branch
        include_match: ^.*$
    context:
      tasks:
        build:
          traits:
            nodejs: true
            Leiningen: true
            JDK: true
            g2016: true
          scripts:
            prepare:
              body: ./bin/prepare
            build-shared:
              body: ./bin/build-shared
              start_when:
                prepare has passed:
                  script_key: prepare
            build-mac-os:
              body: |
                set -eoux
                ./bin/build-mac-os
                zip -r /tmp/Madek-App_Mac-OS_${CIDER_CI_TREE_ID}.zip madek-app-darwin-x64
              start_when:
                build-shared has passed:
                  script_key: build-shared
